[platformio]
src_dir = TamaFi/TamaFi
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/Bodmer/TFT_eSPI.git
    https://github.com/bitbank2/PNGdec.git
    adafruit/Adafruit NeoPixel

build_flags =
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=45
    -D TFT_SCLK=40
    -D TFT_CS=39
    -D TFT_DC=41
    -D TFT_RST=42
    -D TFT_BL=48
    -D TFT_BACKLIGHT_ON=HIGH

